/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class SWIGTYPE_p_java_wxwindow {
  private long swigCPtr;

  protected SWIGTYPE_p_java_wxwindow(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_java_wxwindow() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_java_wxwindow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

