/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxwindow_moduleJNI {
  public final static native long new_java_wxwindow__SWIG_0(long jarg1, java_wxwindow jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, String jarg8);
  public final static native long new_java_wxwindow__SWIG_1();
  public final static native void delete_java_wxwindow(long jarg1);

	static {
		System.loadLibrary("wxwindow");
	}

}
